<?php
/******************************************************************************
 * TouchMe, an ldap dialer add-on for Asterisk-based PBX systems.
 * Copyright (C) 2008 Exalead SA.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************************/
/******************************************************************************
 *
 *                            Main include file
 *
 *****************************************************************************/

/* Lang */
require_once('lang.inc');

/* LDAP Client */
require_once('ldap.inc');

/* Call Manager */
require_once('callmanager.inc');

/* Auth */
require_once('auth.inc');

/* Configuration helpers */
require_once('confighelpers.inc');

/* Version */
require_once('version.inc');

?>
